scheme: "default"
author: "codio"
base00: "fffffe" # Default Background
base01: "f2f2f2" # Lighter Background (Used for status bars, line number and folding marks)
base02: "ADD6FF" # Selection Background
base03: "008000" # Comments, Invisibles, Line Highlighting
base04: "ebebeb" # Dark Foreground (Used for status bars)
base05: "000000" # Default Foreground, Caret, Delimiters, Operators
base06: "000000" # Light Foreground (Not often used)
base07: "000000" # Light Background (Not often used)
base08: "0b0bff" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09: "098658" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A: "000000" # Classes, Markup Bold, Search Text Background
base0B: "a31515" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C: "800000" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D: "000000" # Functions, Methods, Attribute IDs, Headings
base0E: "0000ff" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F: "000000" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
